dist: focal  # https://docs.travis-ci.com/user/reference/linux
language: python

jobs:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: linux
      python: 3.9

install:
  - python --version
  - python -m pip install --upgrade pip
  - python -m pip install --upgrade setuptools wheel
  - python -m pip install --upgrade --editable .[tests]

script:
  - python -m pytest
